"""add visualization users

Revision ID: 6cb74aa2d44c
Revises: 9a0d6e4ae5de
Create Date: 2026-05-19 19:00:15.853261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb74aa2d44c'
down_revision = '9a0d6e4ae5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visualization_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('access_role', sa.String(length=50), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    with op.batch_alter_table('visualization_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visualization_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visualization_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visualization_users_username'))

    op.drop_table('visualization_users')
    # ### end Alembic commands ###
