"""add viewer users

Revision ID: 9a0d6e4ae5de
Revises: a1f11372396e
Create Date: 2026-05-19 11:15:08.847457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0d6e4ae5de'
down_revision = 'a1f11372396e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewer_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('is_active_user', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    with op.batch_alter_table('viewer_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viewer_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewer_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viewer_users_username'))

    op.drop_table('viewer_users')
    # ### end Alembic commands ###
